//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CappuChat.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CappuChat.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string AppSettingsWindowTitle {
            get {
                return ResourceManager.GetString("AppSettingsWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cappu Call! ANSWER NOW!!.
        /// </summary>
        public static string CappuCalled {
            get {
                return ResourceManager.GetString("CappuCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cappu Vote - Overview.
        /// </summary>
        public static string CappuCallOverview {
            get {
                return ResourceManager.GetString("CappuCallOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Got it!.
        /// </summary>
        public static string Changelog_GotIt {
            get {
                return ResourceManager.GetString("Changelog_GotIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whats new?.
        /// </summary>
        public static string Changelog_Title {
            get {
                return ResourceManager.GetString("Changelog_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type a message....
        /// </summary>
        public static string ChatInput_Watermark {
            get {
                return ResourceManager.GetString("ChatInput_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chats.
        /// </summary>
        public static string Chats {
            get {
                return ResourceManager.GetString("Chats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to try reconnecting.
        /// </summary>
        public static string ClickToReconnect {
            get {
                return ResourceManager.GetString("ClickToReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to server.
        /// </summary>
        public static string ConnectedToServer {
            get {
                return ResourceManager.GetString("ConnectedToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cappu Call.
        /// </summary>
        public static string CreateVote {
            get {
                return ResourceManager.GetString("CreateVote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string GoCall {
            get {
                return ResourceManager.GetString("GoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GOGOOGOGOGOOGOGOGOGOIOGOGOGO.
        /// </summary>
        public static string GoGoCall {
            get {
                return ResourceManager.GetString("GoGoCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged out.
        /// </summary>
        public static string LoggedOut {
            get {
                return ResourceManager.GetString("LoggedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You were logged out. Reason: {0}.
        /// </summary>
        public static string LoggedOut_Reason {
            get {
                return ResourceManager.GetString("LoggedOut_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed.
        /// </summary>
        public static string LoginFailed {
            get {
                return ResourceManager.GetString("LoginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failed. Reason: {0}.
        /// </summary>
        public static string LoginFailed_Reason {
            get {
                return ResourceManager.GetString("LoginFailed_Reason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LogOut.
        /// </summary>
        public static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No chat selected.
        /// </summary>
        public static string NoChatSelected {
            get {
                return ResourceManager.GetString("NoChatSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not connected to server.
        /// </summary>
        public static string NotConnectedToServer {
            get {
                return ResourceManager.GetString("NotConnectedToServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not voted yet.
        /// </summary>
        public static string NotVoted {
            get {
                return ResourceManager.GetString("NotVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whats your password?....
        /// </summary>
        public static string Password_Watermark {
            get {
                return ResourceManager.GetString("Password_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;(DM) {0}: {1}&quot;.
        /// </summary>
        public static string PrivateMessageNotification_UserName_Message {
            get {
                return ResourceManager.GetString("PrivateMessageNotification_UserName_Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notifications off.
        /// </summary>
        public static string PushNotificationsOff {
            get {
                return ResourceManager.GetString("PushNotificationsOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push notifications on.
        /// </summary>
        public static string PushNotificationsOn {
            get {
                return ResourceManager.GetString("PushNotificationsOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register failed.
        /// </summary>
        public static string RegistrationFailed {
            get {
                return ResourceManager.GetString("RegistrationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart is required.
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due to your changes you need to restart the client!.
        /// </summary>
        public static string RestartRequiredContent {
            get {
                return ResourceManager.GetString("RestartRequiredContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server connection was lost. Restarting....
        /// </summary>
        public static string RestartRequiredServerConnection {
            get {
                return ResourceManager.GetString("RestartRequiredServerConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Port....
        /// </summary>
        public static string ServerPort_Watermark {
            get {
                return ResourceManager.GetString("ServerPort_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server settings.
        /// </summary>
        public static string ServerSettings {
            get {
                return ResourceManager.GetString("ServerSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server Url....
        /// </summary>
        public static string ServerUrl_Watermark {
            get {
                return ResourceManager.GetString("ServerUrl_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Settings_FTP_Password {
            get {
                return ResourceManager.GetString("Settings_FTP_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Settings_FTP_Username {
            get {
                return ResourceManager.GetString("Settings_FTP_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host.
        /// </summary>
        public static string Settings_Host {
            get {
                return ResourceManager.GetString("Settings_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port.
        /// </summary>
        public static string Settings_Port {
            get {
                return ResourceManager.GetString("Settings_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Theme.
        /// </summary>
        public static string Settings_Theme {
            get {
                return ResourceManager.GetString("Settings_Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong....
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Already....
        /// </summary>
        public static string TitleVoteAlreadyCreated {
            get {
                return ResourceManager.GetString("TitleVoteAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users online:.
        /// </summary>
        public static string UserInGroupChat {
            get {
                return ResourceManager.GetString("UserInGroupChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whats your username?....
        /// </summary>
        public static string Username_Watermark {
            get {
                return ResourceManager.GetString("Username_Watermark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Too late.. vote already created by someone else....
        /// </summary>
        public static string VoteAlreadyCreated {
            get {
                return ResourceManager.GetString("VoteAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voted.
        /// </summary>
        public static string Voted {
            get {
                return ResourceManager.GetString("Voted", resourceCulture);
            }
        }
    }
}
